import type {
  AgentDefinition,
  AgentReleaseRecord,
  AgentVersionRecord,
  Artifact,
  AuditEvent,
  ConnectorDefinition,
  HealthComponent,
  MemberDefinition,
  ModelUsageRecord,
  RoleDefinition,
  RuntimeDefinition,
  SkillDefinition,
  TaskRun,
  ToolDefinition,
  UsagePoint,
  UserProfile,
  Workspace,
} from '../../domain/types.ts'

export const prototypeUsers: Record<UserProfile['role'], UserProfile> = {
  employee: {
    id: 'U10086',
    name: '林岚',
    title: '生产计划专员',
    department: '供应链中心',
    avatarText: '林',
    role: 'employee',
    dataScopes: ['工厂一', '华东仓'],
  },
  department_manager: {
    id: 'U10021',
    name: '周衡',
    title: '供应链负责人',
    department: '供应链中心',
    avatarText: '周',
    role: 'department_manager',
    dataScopes: ['供应链中心', '工厂一', '工厂二'],
  },
  platform_admin: {
    id: 'U00008',
    name: '陈默',
    title: 'AI 平台管理员',
    department: '数字化中心',
    avatarText: '陈',
    role: 'platform_admin',
    dataScopes: ['平台配置'],
  },
  auditor: {
    id: 'U00019',
    name: '沈清',
    title: '安全审计员',
    department: '信息安全部',
    avatarText: '沈',
    role: 'auditor',
    dataScopes: ['授权审计记录'],
  },
}

const shortageSteps = [
  {
    id: 'step-1',
    title: '识别订单与查询范围',
    detail: '已识别销售订单 SO20260821001，数据范围为工厂一与华东仓。',
    status: 'succeeded' as const,
    duration: '0.8 秒',
  },
  {
    id: 'step-2',
    title: '查询订单与生产工单',
    detail: '已读取订单行及关联的 3 张生产工单。',
    status: 'succeeded' as const,
    tool: 'erp.get_sales_order',
    duration: '1.4 秒',
  },
  {
    id: 'step-3',
    title: '核对生产进度',
    detail: '正在比对计划数量、完工数量与交付日期。',
    status: 'running' as const,
    tool: 'mes.get_work_order_progress',
  },
  {
    id: 'step-4',
    title: '核对库存与采购到货',
    detail: '等待上一步完成。',
    status: 'pending' as const,
    tool: 'wms.get_material_inventory',
  },
  {
    id: 'step-5',
    title: '生成缺料风险结论',
    detail: '等待数据准备完成。',
    status: 'pending' as const,
  },
]

export const mockTasks: TaskRun[] = [
  {
    id: 'run-260828-002',
    attemptId: 'attempt-run-260828-002-1',
    title: '核查 SO20260821001 缺料风险',
    prompt: '查询订单 SO20260821001 当前生产进度，判断是否存在缺料风险。',
    status: 'running',
    workspaceId: 'ws-supply',
    workspaceName: '供应链经营分析',
    sessionId: 'session-1002',
    agentVersion: 'dsh-work-assistant@1.2.0',
    createdAt: '今天 10:42',
    updatedAt: '刚刚',
    owner: '林岚',
    messages: [
      {
        id: 'msg-1',
        role: 'user',
        content: '查询订单 SO20260821001 当前生产进度，判断是否存在缺料风险。',
        createdAt: '10:42',
      },
      {
        id: 'msg-2',
        role: 'assistant',
        content: '正在核对订单、生产工单、库存和采购到货计划。我会在数据准备完成后给出风险清单和建议。',
        createdAt: '10:42',
      },
    ],
    steps: shortageSteps,
    sources: [],
    artifacts: [],
    attachments: [],
  },
  {
    id: 'run-260828-001',
    attemptId: 'attempt-run-260828-001-1',
    title: '分析华东区本月订单交付风险',
    prompt: '分析华东区本月订单交付情况，找出延期风险最高的订单并给出跟进建议。',
    status: 'succeeded',
    workspaceId: 'ws-supply',
    workspaceName: '供应链经营分析',
    sessionId: 'session-1001',
    agentVersion: 'dsh-work-assistant@1.2.0',
    createdAt: '今天 09:18',
    updatedAt: '今天 09:22',
    duration: '3 分 42 秒',
    tokenUsage: 18340,
    owner: '林岚',
    messages: [
      {
        id: 'msg-11',
        role: 'user',
        content: '分析华东区本月订单交付情况，找出延期风险最高的订单并给出跟进建议。',
        createdAt: '09:18',
      },
      {
        id: 'msg-12',
        role: 'assistant',
        content:
          '本月华东区共有 126 张在制订单，其中 8 张存在延期风险。高风险订单集中在电机组件与控制器两类物料，主要受供应商到货延迟影响。建议优先协调 SO20260821001、SO20260821018 和 SO20260821027，并在 8 月 30 日前确认替代料方案。',
        createdAt: '09:22',
      },
    ],
    steps: [
      {
        id: 'done-1',
        title: '确定统计范围',
        detail: '华东区，统计周期 2026-08-01 至 2026-08-28。',
        status: 'succeeded',
        duration: '0.6 秒',
      },
      {
        id: 'done-2',
        title: '读取订单和生产进度',
        detail: '查询 126 张在制订单及其关联工单。',
        status: 'succeeded',
        tool: 'erp.get_orders + mes.get_work_order_progress',
        duration: '38 秒',
      },
      {
        id: 'done-3',
        title: '核对库存与到货计划',
        detail: '识别 14 项关键物料的库存和采购承诺日期。',
        status: 'succeeded',
        tool: 'wms.get_inventory + procurement.get_delivery_plan',
        duration: '54 秒',
      },
      {
        id: 'done-4',
        title: '生成风险分级与建议',
        detail: '形成 3 张高风险、5 张中风险订单清单。',
        status: 'succeeded',
        duration: '1 分 26 秒',
      },
    ],
    sources: [
      {
        id: 'src-1',
        type: 'erp',
        title: 'ERP · 销售订单',
        description: '126 张华东区在制订单，字段已按当前用户数据范围过滤。',
        updatedAt: '2026-08-28 09:19',
      },
      {
        id: 'src-2',
        type: 'mes',
        title: 'MES · 生产工单进度',
        description: '关联 184 张生产工单的计划、开工与完工数据。',
        updatedAt: '2026-08-28 09:20',
      },
      {
        id: 'src-3',
        type: 'erp',
        title: '采购平台 · 到货计划',
        description: '关键物料未来 14 天供应商承诺到货计划。',
        updatedAt: '2026-08-28 09:20',
      },
    ],
    artifacts: [
      {
        id: 'artifact-001',
        name: '华东区订单交付风险清单.xlsx',
        type: 'xlsx',
        version: 1,
        size: '284 KB',
        createdAt: '今天 09:22',
        runId: 'run-260828-001',
        workspaceId: 'ws-supply',
        summary: '包含 8 张风险订单、风险原因、责任部门和建议完成日期。',
      },
      {
        id: 'artifact-002',
        name: '华东区交付风险分析报告.pdf',
        type: 'pdf',
        version: 1,
        size: '1.8 MB',
        createdAt: '今天 09:22',
        runId: 'run-260828-001',
        workspaceId: 'ws-supply',
        summary: '经营摘要、风险分布和重点订单处置建议。',
      },
    ],
    attachments: [],
    summary: '识别 8 张风险订单，其中 3 张需要在 48 小时内处理。',
  },
  {
    id: 'run-260827-004',
    attemptId: 'attempt-run-260827-004-1',
    title: '分析八月生产计划文件',
    prompt: '分析上传的八月生产计划，结合当前库存标出下周可能缺料的订单。',
    status: 'awaiting_approval',
    workspaceId: 'ws-supply',
    workspaceName: '供应链经营分析',
    sessionId: 'session-0998',
    agentVersion: 'dsh-work-assistant@1.2.0',
    createdAt: '昨天 16:08',
    updatedAt: '昨天 16:10',
    owner: '林岚',
    messages: [
      {
        id: 'msg-21',
        role: 'user',
        content: '分析上传的八月生产计划，结合当前库存标出下周可能缺料的订单。',
        createdAt: '昨天 16:08',
      },
      {
        id: 'msg-22',
        role: 'assistant',
        content: '生产计划已完成解析。继续查询 ERP 订单明细需要你的确认，查询范围仅限工厂一。',
        createdAt: '昨天 16:10',
      },
    ],
    steps: [
      {
        id: 'approve-1',
        title: '解析生产计划文件',
        detail: '读取 286 行计划记录，识别 42 张生产订单。',
        status: 'succeeded',
        tool: 'document.extract',
        duration: '11 秒',
      },
      {
        id: 'approve-2',
        title: '确认 ERP 数据查询',
        detail: '将查询工厂一范围内 42 张订单的物料需求和库存数据。',
        status: 'awaiting_approval',
        tool: 'erp.get_order_materials',
      },
      {
        id: 'approve-3',
        title: '生成缺料分析',
        detail: '等待授权。',
        status: 'pending',
      },
    ],
    sources: [
      {
        id: 'src-file-1',
        type: 'file',
        title: '八月生产计划_v3.xlsx',
        description: '用户上传文件，共 286 行有效数据。',
      },
    ],
    artifacts: [],
    attachments: ['八月生产计划_v3.xlsx'],
  },
  {
    id: 'run-260827-002',
    attemptId: 'attempt-run-260827-002-1',
    title: '查询委外加工发料制度',
    prompt: '公司的委外加工业务应该如何处理发料和库存扣减？',
    status: 'succeeded',
    workspaceId: 'ws-personal-U10086',
    workspaceName: '我的空间',
    sessionId: 'session-0991',
    agentVersion: 'dsh-work-assistant@1.1.0',
    createdAt: '昨天 11:32',
    updatedAt: '昨天 11:33',
    duration: '48 秒',
    tokenUsage: 4260,
    owner: '林岚',
    messages: [
      {
        id: 'msg-31',
        role: 'user',
        content: '公司的委外加工业务应该如何处理发料和库存扣减？',
        createdAt: '昨天 11:32',
      },
      {
        id: 'msg-32',
        role: 'assistant',
        content: '委外加工发料应依据已审核的委外订单执行，仓库按委外领料单出库，材料仍计入企业委外库存。供应商报工或收货后，系统按 BOM 定额与允许损耗进行扣减。超耗部分需由采购和生产部门确认后单独处理。',
        createdAt: '昨天 11:33',
      },
    ],
    steps: [
      {
        id: 'knowledge-1',
        title: '检索制度与操作规范',
        detail: '检索到 3 份当前有效文件。',
        status: 'succeeded',
        tool: 'knowledge.search',
        duration: '1.8 秒',
      },
      {
        id: 'knowledge-2',
        title: '核对文档版本',
        detail: '已排除 1 份历史版本。',
        status: 'succeeded',
        duration: '0.4 秒',
      },
      {
        id: 'knowledge-3',
        title: '整理答案与依据',
        detail: '答案仅使用当前有效制度内容。',
        status: 'succeeded',
        duration: '19 秒',
      },
    ],
    sources: [
      {
        id: 'src-k1',
        type: 'knowledge',
        title: '《委外加工业务管理办法》V3.2',
        description: '第 4.1～4.6 节：委外发料、在途与材料核销。',
        updatedAt: '2026-06-12',
      },
      {
        id: 'src-k2',
        type: 'knowledge',
        title: '《仓储出入库操作规范》V5.0',
        description: '第 7 节：委外领料单与库存转移。',
        updatedAt: '2026-07-03',
      },
    ],
    artifacts: [],
    attachments: [],
  },
  {
    id: 'run-260826-008',
    attemptId: 'attempt-run-260826-008-1',
    title: '汇总供应商延期到货记录',
    prompt: '汇总上周供应商延期到货记录并生成表格。',
    status: 'failed',
    workspaceId: 'ws-supply',
    workspaceName: '供应链经营分析',
    sessionId: 'session-0982',
    agentVersion: 'dsh-work-assistant@1.1.0',
    createdAt: '周三 15:21',
    updatedAt: '周三 15:23',
    duration: '2 分 04 秒',
    owner: '林岚',
    messages: [
      {
        id: 'msg-41',
        role: 'user',
        content: '汇总上周供应商延期到货记录并生成表格。',
        createdAt: '周三 15:21',
      },
      {
        id: 'msg-42',
        role: 'assistant',
        content: '采购平台连接超时，本轮查询未能完成。已保留查询条件，可以直接重试。',
        createdAt: '周三 15:23',
      },
    ],
    steps: [
      {
        id: 'failed-1',
        title: '确定统计范围',
        detail: '统计周期为 2026-08-17 至 2026-08-23。',
        status: 'succeeded',
        duration: '0.5 秒',
      },
      {
        id: 'failed-2',
        title: '查询采购到货记录',
        detail: '采购平台在 30 秒内未返回数据，有限重试 2 次后停止。',
        status: 'failed',
        tool: 'procurement.get_delivery_records',
        duration: '1 分 32 秒',
      },
      {
        id: 'failed-3',
        title: '生成延期汇总',
        detail: '因上游数据不可用而跳过。',
        status: 'pending',
      },
    ],
    sources: [],
    artifacts: [],
    attachments: [],
    error: {
      code: 'CONNECTOR_TIMEOUT',
      message: '采购平台连接超时，未获取到完整数据。',
      object: '运行 run-260828-005',
      reason: '采购平台连接器在规定时间内没有返回完整数据。',
      suggestion: '请稍后重试；如持续失败，请联系数字化中心检查采购平台连接器。',
      retryable: true,
    },
  },
]

export const mockWorkspaces: Workspace[] = [
  {
    id: 'ws-personal-U10086',
    name: '我的空间',
    description: '仅你可访问的默认工作空间，用于归档个人对话、文件和成果。',
    type: 'personal',
    memberCount: 1,
    sessionCount: 1,
    artifactCount: 0,
    updatedAt: '昨天 11:33',
    owner: '林岚',
    members: ['林岚'],
    files: [],
  },
  {
    id: 'ws-supply',
    name: '供应链经营分析',
    description: '订单交付、库存、生产进度和采购到货的持续分析空间。',
    type: 'team',
    memberCount: 8,
    sessionCount: 24,
    artifactCount: 16,
    updatedAt: '10 分钟前',
    owner: '供应链中心',
    members: ['周衡', '林岚', '赵宁', '王呈'],
    files: [
      {
        id: 'file-1',
        name: '八月生产计划_v3.xlsx',
        type: 'XLSX',
        size: '3.4 MB',
        uploadedBy: '林岚',
        uploadedAt: '昨天 16:08',
      },
      {
        id: 'file-2',
        name: '华东区交付口径说明.docx',
        type: 'DOCX',
        size: '860 KB',
        uploadedBy: '周衡',
        uploadedAt: '8 月 24 日',
      },
    ],
  },
  {
    id: 'ws-operations',
    name: '月度经营复盘',
    description: '部门经营指标、异常事项和月度分析成果归档。',
    type: 'team',
    memberCount: 5,
    sessionCount: 9,
    artifactCount: 11,
    updatedAt: '3 天前',
    owner: '供应链中心',
    members: ['周衡', '林岚', '孙淼'],
    files: [],
  },
]

export const mockRuntimes: RuntimeDefinition[] = [
  {
    id: 'runtime-prototype-01',
    name: '原型 Runtime',
    environment: '本地原型',
    mode: 'prototype',
    status: 'healthy',
    schedulingStatus: 'accepting',
    version: 'prototype-0.1.0',
    endpoint: '127.0.0.1（前端模拟）',
    maxConcurrentWorkers: 4,
    activeWorkers: 2,
    queuedRuns: 1,
    attemptTimeoutMinutes: 30,
    cpuUsage: '18%',
    memoryUsage: '34%',
    latency: '12 ms',
    lastHeartbeat: '刚刚',
    checkedAt: '刚刚',
    healthMessage: '仅用于演示调度、容量和会话关联，不代表 DSH Worker 已接入。',
    capabilities: ['Agent Loop 演示', 'Skill 加载演示', '预置工具校验', '会话状态模拟'],
  },
  {
    id: 'runtime-production-01',
    name: '生产 Runtime 01',
    environment: '生产目标环境',
    mode: 'dsh-worker',
    status: 'offline',
    schedulingStatus: 'disabled',
    version: '待安装',
    endpoint: '待配置',
    maxConcurrentWorkers: 8,
    activeWorkers: 0,
    queuedRuns: 0,
    attemptTimeoutMinutes: 30,
    cpuUsage: '—',
    memoryUsage: '—',
    latency: '—',
    lastHeartbeat: '从未连接',
    checkedAt: '尚未检查',
    healthMessage: '一期实施时安装 DSH Worker 并完成 Runtime Adapter 注册。',
    capabilities: ['Agent Loop', 'Tools', 'Skills', 'Session', 'Approval', 'Sandbox'],
  },
  {
    id: 'runtime-dr-01',
    name: '灾备 Runtime 01',
    environment: '灾备目标环境',
    mode: 'dsh-worker',
    status: 'offline',
    schedulingStatus: 'disabled',
    version: '待规划',
    endpoint: '待配置',
    maxConcurrentWorkers: 8,
    activeWorkers: 0,
    queuedRuns: 0,
    attemptTimeoutMinutes: 30,
    cpuUsage: '—',
    memoryUsage: '—',
    latency: '—',
    lastHeartbeat: '从未连接',
    checkedAt: '尚未检查',
    healthMessage: '非 MVP 必需节点，生产稳定后再按容量和容灾要求启用。',
    capabilities: ['会话恢复', '故障接管', '隔离执行'],
  },
]

export const mockArtifacts: Artifact[] = [
  ...mockTasks.flatMap((task) => task.artifacts),
  {
    id: 'artifact-010',
    name: '七月供应链经营分析.docx',
    type: 'docx',
    version: 3,
    size: '2.6 MB',
    createdAt: '8 月 5 日',
    runId: 'run-260805-014',
    workspaceId: 'ws-operations',
    summary: '七月订单、库存和供应商交付情况的正式归档版本。',
  },
  {
    id: 'artifact-011',
    name: '高频缺料物料清单.xlsx',
    type: 'xlsx',
    version: 2,
    size: '460 KB',
    createdAt: '8 月 2 日',
    runId: 'run-260802-006',
    workspaceId: 'ws-supply',
    summary: '过去 90 天出现三次及以上缺料的物料与供应商信息。',
  },
]

export const mockAgents: AgentDefinition[] = [
  {
    id: 'dsh-work-assistant',
    name: 'dsh-work Assistant',
    description: '员工统一 AI 对话入口，可处理企业知识、业务查询和文件分析。',
    owner: '陈默',
    department: '数字化中心',
    visibility: '全体试点员工',
    roleIds: ['role-employee', 'role-supply', 'role-manager'],
    dataScopes: ['继承员工角色与工作空间数据范围'],
    status: 'published',
    version: '1.2.0',
    welcomeMessage: '你好，我可以帮助你查询企业知识、分析业务数据和处理文件。',
    examplePrompts: ['查询订单交付风险', '分析库存并生成风险清单', '总结这份业务文件'],
    systemPrompt: '你是 dsh-work 企业 AI 助手。仅在当前员工权限和工作空间范围内检索数据，执行敏感操作前必须获得确认，并清晰标注结论来源。',
    maxTokens: 12000,
    timeoutSeconds: 300,
    skills: ['企业知识问答', '订单分析', '缺料风险分析', '表格分析'],
    tools: ['knowledge.search', 'erp.get_sales_order', 'mes.get_work_order_progress'],
    updatedAt: '2026-08-27 17:42',
  },
  {
    id: 'operations-analyst',
    name: '经营分析助手',
    description: '面向部门负责人的经营指标分析入口，当前处于评审阶段。',
    owner: '周衡',
    department: '供应链中心',
    visibility: '供应链中心',
    roleIds: ['role-supply', 'role-manager'],
    dataScopes: ['供应链中心', '本部门汇总数据'],
    status: 'draft',
    version: '0.4.0',
    welcomeMessage: '请告诉我需要分析的经营主题、统计范围和时间周期。',
    examplePrompts: ['分析本月订单交付情况', '生成库存周转经营摘要'],
    systemPrompt: '你是供应链经营分析助手。使用统一指标口径组织分析，只读取当前用户已授权的汇总数据，并在结论中说明统计范围、时间周期和数据来源。',
    maxTokens: 16000,
    timeoutSeconds: 360,
    skills: ['订单分析', '表格分析'],
    tools: ['erp.get_orders', 'artifact.publish'],
    updatedAt: '2026-08-28 09:14',
  },
]

export const mockAgentVersions: AgentVersionRecord[] = [
  {
    id: 'agent-version-assistant-120',
    agentId: 'dsh-work-assistant',
    version: '1.2.0',
    status: 'published',
    createdAt: '2026-08-26 14:20',
    createdBy: '陈默',
    publishedAt: '2026-08-27 17:42',
    publishedBy: '陈默',
    sourceVersion: '1.1.0',
    summary: '新增缺料风险分析 Skill，并完成敏感数据安全校验。',
    visibility: '全体试点员工',
    roleIds: ['role-employee', 'role-supply', 'role-manager'],
    dataScopes: ['继承员工角色与工作空间数据范围'],
    welcomeMessage: '你好，我可以帮助你查询企业知识、分析业务数据和处理文件。',
    examplePrompts: ['查询订单交付风险', '分析库存并生成风险清单', '总结这份业务文件'],
    systemPrompt: '你是 dsh-work 企业 AI 助手。仅在当前员工权限和工作空间范围内检索数据，执行敏感操作前必须获得确认，并清晰标注结论来源。',
    maxTokens: 12000,
    timeoutSeconds: 300,
    skills: ['企业知识问答', '订单分析', '缺料风险分析', '表格分析'],
    tools: ['knowledge.search', 'erp.get_sales_order', 'mes.get_work_order_progress'],
  },
  {
    id: 'agent-version-assistant-110',
    agentId: 'dsh-work-assistant',
    version: '1.1.0',
    status: 'published',
    createdAt: '2026-08-12 10:15',
    createdBy: '陈默',
    publishedAt: '2026-08-13 09:30',
    publishedBy: '陈默',
    sourceVersion: '1.0.0',
    summary: '增加订单分析和表格分析能力。',
    visibility: '全体试点员工',
    roleIds: ['role-employee', 'role-supply', 'role-manager'],
    dataScopes: ['继承员工角色与工作空间数据范围'],
    welcomeMessage: '你好，我可以帮助你查询企业知识、分析业务数据和处理文件。',
    examplePrompts: ['查询订单交付风险', '总结这份业务文件'],
    systemPrompt: '你是 dsh-work 企业 AI 助手。仅使用员工有权访问的数据回答问题，并标明使用的数据来源。',
    maxTokens: 10000,
    timeoutSeconds: 300,
    skills: ['企业知识问答', '订单分析', '表格分析'],
    tools: ['knowledge.search', 'erp.get_sales_order'],
  },
  {
    id: 'agent-version-assistant-100',
    agentId: 'dsh-work-assistant',
    version: '1.0.0',
    status: 'disabled',
    createdAt: '2026-08-01 11:06',
    createdBy: '陈默',
    publishedAt: '2026-08-03 15:18',
    publishedBy: '陈默',
    summary: '首个试点版本，仅支持企业知识问答。',
    visibility: '全体试点员工',
    roleIds: ['role-employee'],
    dataScopes: ['企业公开知识', '当前有效制度'],
    welcomeMessage: '你好，我可以帮助你查询企业制度和业务资料。',
    examplePrompts: ['查询公司的委外加工制度'],
    systemPrompt: '你是企业知识问答助手。只依据当前有效的企业制度回答，并展示引用来源。',
    maxTokens: 8000,
    timeoutSeconds: 180,
    skills: ['企业知识问答'],
    tools: ['knowledge.search'],
  },
  {
    id: 'agent-version-operations-040',
    agentId: 'operations-analyst',
    version: '0.4.0',
    status: 'draft',
    createdAt: '2026-08-28 09:14',
    createdBy: '周衡',
    sourceVersion: '0.3.0',
    summary: '新增敏感经营数据访问范围，等待发布评审。',
    visibility: '供应链中心',
    roleIds: ['role-supply', 'role-manager'],
    dataScopes: ['供应链中心', '本部门汇总数据'],
    welcomeMessage: '请告诉我需要分析的经营主题、统计范围和时间周期。',
    examplePrompts: ['分析本月订单交付情况', '生成库存周转经营摘要'],
    systemPrompt: '你是供应链经营分析助手。使用统一指标口径组织分析，只读取当前用户已授权的汇总数据，并在结论中说明统计范围、时间周期和数据来源。',
    maxTokens: 16000,
    timeoutSeconds: 360,
    skills: ['订单分析', '表格分析'],
    tools: ['erp.get_orders', 'artifact.publish'],
  },
  {
    id: 'agent-version-operations-030',
    agentId: 'operations-analyst',
    version: '0.3.0',
    status: 'published',
    createdAt: '2026-08-18 13:45',
    createdBy: '周衡',
    publishedAt: '2026-08-20 16:10',
    publishedBy: '陈默',
    summary: '经营分析试用版本。',
    visibility: '供应链中心',
    roleIds: ['role-manager'],
    dataScopes: ['本部门汇总数据'],
    welcomeMessage: '请告诉我需要分析的经营主题和时间周期。',
    examplePrompts: ['分析本月订单交付情况'],
    systemPrompt: '你是供应链经营分析助手。只读取当前负责人有权查看的部门汇总数据，并说明指标口径。',
    maxTokens: 12000,
    timeoutSeconds: 300,
    skills: ['订单分析'],
    tools: ['erp.get_orders'],
  },
]

export const mockAgentReleaseRecords: AgentReleaseRecord[] = [
  { id: 'release-006', agentId: 'dsh-work-assistant', version: '1.2.0', action: 'published', actor: '陈默', time: '2026-08-27 17:42', note: '通过回归测试与安全评审，发布至全体试点员工。' },
  { id: 'release-005', agentId: 'dsh-work-assistant', version: '1.1.0', action: 'enabled', actor: '陈默', time: '2026-08-21 09:05', note: '试点问题修复后重新启用。' },
  { id: 'release-004', agentId: 'dsh-work-assistant', version: '1.1.0', action: 'disabled', actor: '沈清', time: '2026-08-20 18:26', note: '安全检查期间临时停用。' },
  { id: 'release-003', agentId: 'dsh-work-assistant', version: '1.1.0', action: 'published', actor: '陈默', time: '2026-08-13 09:30', note: '新增订单分析能力。' },
  { id: 'release-002', agentId: 'operations-analyst', version: '0.3.0', action: 'published', actor: '陈默', time: '2026-08-20 16:10', note: '仅向供应链中心灰度发布。' },
  { id: 'release-001', agentId: 'dsh-work-assistant', version: '1.0.0', action: 'published', actor: '陈默', time: '2026-08-03 15:18', note: '首个企业知识问答试点版本。' },
]

export const mockSkills: SkillDefinition[] = [
  {
    id: 'enterprise-knowledge',
    name: '企业知识问答',
    version: '1.1.0',
    category: '知识',
    owner: '知识运营组',
    status: 'published',
    description: '检索企业制度和 SOP，依据当前有效版本组织回答。',
    instructions: '先检索当前有效的制度与 SOP，只依据命中的企业资料回答，并在结论后列出来源。',
    toolIds: ['knowledge.search'],
    testPrompt: '差旅报销需要哪些审批材料？',
    updatedAt: '2026-08-26',
  },
  {
    id: 'order-analysis',
    name: '订单分析',
    version: '1.3.0',
    category: '供应链',
    owner: '供应链数字化组',
    status: 'published',
    description: '组合订单、工单、库存和到货计划形成交付分析。',
    instructions: '按订单交付日期聚合销售订单、生产进度与库存信息，标注口径并输出风险排序。',
    toolIds: ['erp.get_sales_order', 'mes.get_work_order_progress', 'wms.get_material_inventory'],
    testPrompt: '分析本月订单交付风险。',
    updatedAt: '2026-08-27',
  },
  {
    id: 'shortage-analysis',
    name: '缺料风险分析',
    version: '1.0.2',
    category: '生产',
    owner: '计划管理部',
    status: 'published',
    description: '根据固定口径评估物料缺口、影响订单与处置优先级。',
    instructions: '读取工单和库存数据，计算预计缺口，按影响订单数量和交期紧迫度给出处置优先级。',
    toolIds: ['mes.get_work_order_progress', 'wms.get_material_inventory'],
    testPrompt: '检查未来两周的缺料风险。',
    updatedAt: '2026-08-24',
  },
  {
    id: 'spreadsheet-analysis',
    name: '表格分析',
    version: '0.9.0',
    category: '文件',
    owner: 'AI 平台组',
    status: 'draft',
    description: '识别 XLSX 和 CSV 结构，完成指标计算与异常检测。',
    instructions: '识别用户上传表格的字段和数据类型，先说明分析口径，再进行指标计算和异常检测。',
    toolIds: ['artifact.publish'],
    testPrompt: '分析上传表格中的异常订单。',
    updatedAt: '2026-08-28',
  },
]

export const mockTools: ToolDefinition[] = [
  {
    id: 'knowledge.search',
    name: '知识检索',
    system: '企业知识库',
    description: '按关键词和访问范围检索当前有效的企业知识文档。',
    connectorId: 'connector-knowledge',
    risk: 'low',
    mode: 'read',
    status: 'available',
    inputSchema: JSON.stringify({ type: 'object', required: ['query'], properties: { query: { type: 'string' }, limit: { type: 'integer', default: 5 } } }, null, 2),
    outputSchema: JSON.stringify({ type: 'object', properties: { documents: { type: 'array' } } }, null, 2),
    timeoutSeconds: 20,
    allowedRoles: ['试点员工'],
    dataScopes: ['企业公开知识', '当前有效制度'],
    approvalPolicy: 'none',
    lastCheckedAt: '1 分钟前',
  },
  {
    id: 'erp.get_sales_order',
    name: '销售订单查询',
    system: 'ERP',
    description: '按销售组织、日期和订单状态查询销售订单。',
    connectorId: 'connector-erp',
    risk: 'medium',
    mode: 'read',
    status: 'available',
    inputSchema: JSON.stringify({ type: 'object', required: ['dateFrom', 'dateTo'], properties: { dateFrom: { type: 'string' }, dateTo: { type: 'string' }, organization: { type: 'string' } } }, null, 2),
    outputSchema: JSON.stringify({ type: 'object', properties: { orders: { type: 'array' } } }, null, 2),
    timeoutSeconds: 30,
    allowedRoles: ['销售', '供应链', '管理者'],
    dataScopes: ['本人所属部门', '已授权销售组织'],
    approvalPolicy: 'sensitive',
    lastCheckedAt: '2 分钟前',
  },
  {
    id: 'mes.get_work_order_progress',
    name: '生产工单进度',
    system: 'MES',
    description: '查询已授权工厂内生产工单的计划与实际进度。',
    connectorId: 'connector-mes',
    risk: 'medium',
    mode: 'read',
    status: 'available',
    inputSchema: JSON.stringify({ type: 'object', required: ['plant'], properties: { plant: { type: 'string' }, orderIds: { type: 'array', items: { type: 'string' } } } }, null, 2),
    outputSchema: JSON.stringify({ type: 'object', properties: { workOrders: { type: 'array' } } }, null, 2),
    timeoutSeconds: 30,
    allowedRoles: ['生产', '供应链', '管理者'],
    dataScopes: ['已授权工厂'],
    approvalPolicy: 'sensitive',
    lastCheckedAt: '2 分钟前',
  },
  {
    id: 'wms.get_material_inventory',
    name: '物料库存查询',
    system: 'WMS',
    description: '查询已授权仓库的物料现存量与可用量。',
    connectorId: 'connector-wms',
    risk: 'medium',
    mode: 'read',
    status: 'degraded',
    inputSchema: JSON.stringify({ type: 'object', required: ['warehouse'], properties: { warehouse: { type: 'string' }, materialIds: { type: 'array', items: { type: 'string' } } } }, null, 2),
    outputSchema: JSON.stringify({ type: 'object', properties: { inventory: { type: 'array' } } }, null, 2),
    timeoutSeconds: 30,
    allowedRoles: ['仓储', '供应链', '管理者'],
    dataScopes: ['已授权仓库'],
    approvalPolicy: 'sensitive',
    lastCheckedAt: '5 分钟前',
  },
  {
    id: 'artifact.publish',
    name: '成果发布',
    system: 'dsh-work',
    description: '将运行结果保存为当前工作空间中的可交付成果。',
    connectorId: '',
    risk: 'low',
    mode: 'write',
    status: 'available',
    inputSchema: JSON.stringify({ type: 'object', required: ['name', 'content'], properties: { name: { type: 'string' }, content: { type: 'string' } } }, null, 2),
    outputSchema: JSON.stringify({ type: 'object', properties: { artifactId: { type: 'string' }, version: { type: 'integer' } } }, null, 2),
    timeoutSeconds: 20,
    allowedRoles: ['试点员工'],
    dataScopes: ['当前工作空间'],
    approvalPolicy: 'none',
    lastCheckedAt: '1 分钟前',
  },
]

export const mockConnectors: ConnectorDefinition[] = [
  {
    id: 'connector-knowledge',
    name: '企业知识库连接器',
    system: '知识平台',
    status: 'healthy',
    toolCount: 2,
    protocol: 'rest',
    endpoint: 'https://knowledge.internal.example/api',
    authType: '服务身份 + 用户范围',
    credentialRef: 'secret://dsh-work/knowledge-service',
    scopeDescription: '继承当前员工可访问的知识空间与文档密级。',
    latency: '182 ms',
    lastCheckedAt: '1 分钟前',
  },
  {
    id: 'connector-erp',
    name: 'ERP 连接器',
    system: 'ERP',
    status: 'healthy',
    toolCount: 4,
    protocol: 'openapi',
    endpoint: 'https://erp.internal.example/openapi',
    authType: '服务身份 + 数据范围',
    credentialRef: 'secret://dsh-work/erp-service',
    scopeDescription: '按员工所属销售组织与已授权公司代码收窄数据范围。',
    latency: '246 ms',
    lastCheckedAt: '2 分钟前',
  },
  {
    id: 'connector-mes',
    name: 'MES 连接器',
    system: 'MES',
    status: 'healthy',
    toolCount: 3,
    protocol: 'rest',
    endpoint: 'https://mes.internal.example/api',
    authType: '服务身份 + 工厂范围',
    credentialRef: 'secret://dsh-work/mes-service',
    scopeDescription: '仅允许访问员工被授权的工厂与生产线。',
    latency: '311 ms',
    lastCheckedAt: '2 分钟前',
  },
  {
    id: 'connector-wms',
    name: 'WMS 连接器',
    system: 'WMS',
    status: 'degraded',
    toolCount: 2,
    protocol: 'rest',
    endpoint: 'https://wms.internal.example/api',
    authType: '服务身份 + 仓库范围',
    credentialRef: 'secret://dsh-work/wms-service',
    scopeDescription: '仅允许访问员工被授权的仓库。',
    latency: '1.8 s',
    lastCheckedAt: '5 分钟前',
  },
]

export const mockRoles: RoleDefinition[] = [
  {
    id: 'role-platform-admin',
    name: '平台管理员',
    userCount: 1,
    agents: ['dsh-work Assistant', '经营分析助手（评审中）'],
    tools: ['全部已注册工具（仅治理配置）'],
    dataScopes: ['平台配置', '脱敏运行元数据'],
    updatedAt: '2026-08-28',
  },
  {
    id: 'role-employee',
    name: '试点员工',
    userCount: 36,
    agents: ['dsh-work Assistant'],
    tools: ['知识检索', '成果发布'],
    dataScopes: ['本人所属部门'],
    updatedAt: '2026-08-26',
  },
  {
    id: 'role-supply',
    name: '供应链分析人员',
    userCount: 12,
    agents: ['dsh-work Assistant'],
    tools: ['订单查询', '生产进度', '库存查询', '采购到货'],
    dataScopes: ['供应链中心', '已授权工厂/仓库'],
    updatedAt: '2026-08-27',
  },
  {
    id: 'role-manager',
    name: '部门负责人',
    userCount: 6,
    agents: ['dsh-work Assistant', '经营分析助手（评审中）'],
    tools: ['部门已授权只读工具'],
    dataScopes: ['本部门汇总数据'],
    updatedAt: '2026-08-27',
  },
  {
    id: 'role-auditor',
    name: '安全审计员',
    userCount: 3,
    agents: [],
    tools: [],
    dataScopes: ['授权审计记录（只读）'],
    updatedAt: '2026-08-25',
  },
]

export const mockMembers: MemberDefinition[] = [
  { id: 'U10086', name: '林岚', title: '生产计划专员', department: '供应链中心', avatarText: '林', roleIds: ['role-employee', 'role-supply'], roleNames: ['试点员工', '供应链分析人员'], status: 'active', ssoStatus: 'synced', dataScopes: ['供应链中心', '工厂一', '华东仓'], lastActiveAt: '今天 10:43' },
  { id: 'U10021', name: '周衡', title: '供应链负责人', department: '供应链中心', avatarText: '周', roleIds: ['role-manager'], roleNames: ['部门负责人'], status: 'active', ssoStatus: 'synced', dataScopes: ['供应链中心', '工厂一', '工厂二'], lastActiveAt: '今天 09:32' },
  { id: 'U00008', name: '陈默', title: 'AI 平台管理员', department: '数字化中心', avatarText: '陈', roleIds: ['role-platform-admin'], roleNames: ['平台管理员'], status: 'active', ssoStatus: 'synced', dataScopes: ['平台配置'], lastActiveAt: '刚刚' },
  { id: 'U00019', name: '沈清', title: '安全审计员', department: '信息安全部', avatarText: '沈', roleIds: ['role-auditor'], roleNames: ['安全审计员'], status: 'active', ssoStatus: 'synced', dataScopes: ['授权审计记录'], lastActiveAt: '昨天 18:26' },
  { id: 'U10218', name: '赵宁', title: '采购专员', department: '采购部', avatarText: '赵', roleIds: ['role-employee'], roleNames: ['试点员工'], status: 'active', ssoStatus: 'synced', dataScopes: ['采购部', '华东供应商'], lastActiveAt: '今天 09:51' },
  { id: 'U10306', name: '王磊', title: '仓储主管', department: '仓储部', avatarText: '王', roleIds: ['role-supply'], roleNames: ['供应链分析人员'], status: 'active', ssoStatus: 'synced', dataScopes: ['华东仓', '华南仓'], lastActiveAt: '昨天 16:08' },
  { id: 'U10412', name: '李娜', title: '质量工程师', department: '质量部', avatarText: '李', roleIds: ['role-employee'], roleNames: ['试点员工'], status: 'active', ssoStatus: 'pending', dataScopes: ['质量部', '工厂一'], lastActiveAt: '尚未登录' },
  { id: 'U09882', name: '张伟', title: '生产调度员', department: '制造中心', avatarText: '张', roleIds: ['role-employee'], roleNames: ['试点员工'], status: 'suspended', ssoStatus: 'synced', dataScopes: ['工厂二'], lastActiveAt: '2026-08-21 14:20' },
]

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'audit-model-001',
    time: '2026-08-28 10:43:22',
    actor: '林岚',
    department: '供应链中心',
    category: 'model', objectType: 'model', objectId: 'DeepSeek-V3', runId: 'run-260828-002', attemptId: 'attempt-demo-001',
    action: '模型调用',
    object: 'DeepSeek-V3 · approved-general',
    status: 'success',
    traceId: 'tr_92af80d18d',
    detail: '输入 2,840 Token，输出 1,126 Token，耗时 2.8 秒；数据等级 L1。',
  },
  {
    id: 'audit-001',
    time: '2026-08-28 10:43:18',
    actor: '林岚',
    department: '供应链中心',
    category: 'tool', objectType: 'tool', objectId: 'mes.get_work_order_progress', runId: 'run-260828-002', attemptId: 'attempt-demo-001',
    action: '工具调用',
    object: 'mes.get_work_order_progress',
    status: 'success',
    traceId: 'tr_92af80d18d',
    detail: '查询订单 SO20260821001 关联工单，数据范围：工厂一。返回 3 条记录。',
  },
  {
    id: 'audit-002',
    time: '2026-08-28 10:42:51',
    actor: '林岚',
    department: '供应链中心',
    category: 'run', objectType: 'run', objectId: 'run-260828-002', runId: 'run-260828-002', attemptId: 'attempt-demo-001',
    action: '创建运行',
    object: 'run-260828-002',
    status: 'success',
    traceId: 'tr_92af80d18d',
    detail: '使用 dsh-work-assistant@1.2.0 发起对话，锁定 approved-general 模型策略。',
  },
  {
    id: 'audit-003',
    time: '2026-08-28 09:51:03',
    actor: '赵宁',
    department: '采购部',
    category: 'tool', objectType: 'tool', objectId: 'erp.get_supplier_price', runId: 'run-260828-003', attemptId: 'attempt-demo-002',
    action: '工具调用',
    object: 'erp.get_supplier_price',
    status: 'blocked',
    traceId: 'tr_3127ad981f',
    detail: '当前角色无供应商价格字段读取权限，请求在连接器网关被阻止。',
  },
  {
    id: 'audit-model-002',
    time: '2026-08-28 09:50:58',
    actor: '赵宁',
    department: '采购部',
    category: 'model', objectType: 'model', objectId: 'approved-general', runId: 'run-260828-003', attemptId: 'attempt-demo-002',
    action: '模型调用',
    object: '外部模型 · approved-general',
    status: 'blocked',
    traceId: 'tr_3127ad981f',
    detail: '请求包含 L2 供应商价格字段，模型策略在调用前阻止数据外发。',
  },
  {
    id: 'audit-004',
    time: '2026-08-28 09:22:14',
    actor: '林岚',
    department: '供应链中心',
    category: 'artifact', objectType: 'artifact', objectId: 'artifact-report-001', runId: 'run-260828-001', attemptId: 'attempt-demo-003',
    action: '发布成果',
    object: '华东区交付风险分析报告.pdf',
    status: 'success',
    traceId: 'tr_abe490071c',
    detail: '发布成果 V1，来源运行：run-260828-001。',
  },
  {
    id: 'audit-005',
    time: '2026-08-27 15:23:28',
    actor: '林岚',
    department: '供应链中心',
    category: 'tool', objectType: 'connector', objectId: 'procurement.get_delivery_records', runId: 'run-260827-004', attemptId: 'attempt-demo-004',
    action: '连接器调用',
    object: 'procurement.get_delivery_records',
    status: 'failed',
    traceId: 'tr_6a7c31e02d',
    detail: '采购平台连接超时，有限重试 2 次后停止。',
  },
]

export const mockHealth: HealthComponent[] = [
  {
    id: 'health-app',
    name: 'dsh-work 原型接口',
    category: 'application',
    status: 'healthy',
    latency: '< 100 ms',
    availability: '当前进程可用',
    message: 'Node.js 模块化单体与两套接口门面运行正常',
    checkedAt: '刚刚',
  },
  {
    id: 'health-worker',
    name: 'DSH 执行进程池',
    category: 'runtime',
    status: 'offline',
    latency: '—',
    availability: '未接入',
    message: '原型尚未连接 DSH 运行时，页面执行过程为前端交互模拟',
    checkedAt: '刚刚',
  },
  {
    id: 'health-model',
    name: '企业模型网关',
    category: 'dependency',
    status: 'offline',
    latency: '—',
    availability: '未配置',
    message: '原型尚未配置模型路由与密钥',
    checkedAt: '刚刚',
  },
  {
    id: 'health-connector',
    name: '企业连接器网关',
    category: 'dependency',
    status: 'offline',
    latency: '—',
    availability: '未配置',
    message: 'ERP、MES、WMS 等连接器均为演示数据',
    checkedAt: '刚刚',
  },
  {
    id: 'health-postgres',
    name: 'PostgreSQL',
    category: 'dependency',
    status: 'offline',
    latency: '—',
    availability: '未配置',
    message: '当前使用进程内原型仓储，不具备持久性',
    checkedAt: '刚刚',
  },
  {
    id: 'health-storage',
    name: '成果存储',
    category: 'dependency',
    status: 'offline',
    latency: '—',
    availability: '未配置',
    message: '文件与成果仅使用原型元数据，尚未接入对象存储',
    checkedAt: '刚刚',
  },
]

export const mockUsage: UsagePoint[] = [
  { day: '08/22', runs: 86, tokens: 520000 },
  { day: '08/23', runs: 103, tokens: 680000 },
  { day: '08/24', runs: 72, tokens: 430000 },
  { day: '08/25', runs: 128, tokens: 880000 },
  { day: '08/26', runs: 145, tokens: 1020000 },
  { day: '08/27', runs: 132, tokens: 910000 },
  { day: '08/28', runs: 96, tokens: 720000 },
]

export const mockModelUsage: ModelUsageRecord[] = [
  { id: 'model-call-001', time: '2026-08-28 10:43:22', runId: 'run-260828-002', agentId: 'dsh-work-assistant', employeeId: 'U10086', employeeName: '林岚', department: '供应链中心', provider: '企业模型网关', model: 'DeepSeek-V3', modelRoute: 'default', dataLevel: 'L1', status: 'success', promptTokens: 2840, completionTokens: 1126, totalTokens: 3966, latencyMs: 2810, costCny: 0.12, traceId: 'tr_92af80d18d' },
  { id: 'model-call-002', time: '2026-08-28 09:51:00', runId: 'run-260828-003', agentId: 'dsh-work-assistant', employeeId: 'U00008', employeeName: '陈默', department: '数字化中心', provider: '企业模型网关', model: '外部模型-自动选择', modelRoute: 'default', dataLevel: 'L2', status: 'blocked', promptTokens: 0, completionTokens: 0, totalTokens: 0, latencyMs: 18, costCny: 0, traceId: 'tr_3127ad981f' },
  { id: 'model-call-003', time: '2026-08-28 09:21:44', runId: 'run-260828-001', agentId: 'dsh-work-assistant', employeeId: 'U10021', employeeName: '周衡', department: '供应链中心', provider: '企业模型网关', model: 'Qwen3-32B', modelRoute: 'analysis', dataLevel: 'L2', status: 'success', promptTokens: 10320, completionTokens: 8020, totalTokens: 18340, latencyMs: 8420, costCny: 0.66, traceId: 'tr_abe490071c' },
  { id: 'model-call-004', time: '2026-08-27 16:09:26', runId: 'run-260827-004', agentId: 'dsh-work-assistant', employeeId: 'U10086', employeeName: '林岚', department: '供应链中心', provider: '企业模型网关', model: 'Qwen3-32B', modelRoute: 'analysis', dataLevel: 'L2', status: 'success', promptTokens: 4822, completionTokens: 1770, totalTokens: 6592, latencyMs: 5180, costCny: 0.24, traceId: 'tr_c4d871e065' },
  { id: 'model-call-005', time: '2026-08-27 15:23:24', runId: 'run-260826-008', agentId: 'dsh-work-assistant', employeeId: 'U10086', employeeName: '林岚', department: '供应链中心', provider: '企业模型网关', model: 'DeepSeek-V3', modelRoute: 'default', dataLevel: 'L1', status: 'failed', promptTokens: 1450, completionTokens: 0, totalTokens: 1450, latencyMs: 30000, costCny: 0.03, traceId: 'tr_6a7c31e02d' },
  { id: 'model-call-006', time: '2026-08-27 11:33:12', runId: 'run-260827-002', agentId: 'dsh-work-assistant', employeeId: 'U10021', employeeName: '周衡', department: '供应链中心', provider: '企业模型网关', model: 'DeepSeek-V3', modelRoute: 'default', dataLevel: 'L1', status: 'success', promptTokens: 2790, completionTokens: 1470, totalTokens: 4260, latencyMs: 1920, costCny: 0.09, traceId: 'tr_628aae109c' },
  { id: 'model-call-007', time: '2026-08-26 14:18:03', runId: 'run-260826-005', agentId: 'operations-analyst', employeeId: 'U10021', employeeName: '周衡', department: '供应链中心', provider: '企业模型网关', model: 'GLM-4.5', modelRoute: 'fallback', dataLevel: 'L1', status: 'success', promptTokens: 6240, completionTokens: 2890, totalTokens: 9130, latencyMs: 4360, costCny: 0.31, traceId: 'tr_70c92ab116' },
]
