-- dsh-work M2 physical schema baseline.
-- IDs are generated by the application so the migration has no extension dependency.

create table if not exists schema_migrations (
  version text primary key,
  applied_at timestamptz not null default now()
);

create table tenants (
  id text primary key,
  name text not null,
  status text not null check (status in ('active', 'disabled')),
  created_at timestamptz not null default now()
);

create table users (
  id text primary key,
  tenant_id text not null references tenants(id),
  external_subject text not null,
  display_name text not null,
  department_id text,
  status text not null check (status in ('active', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, external_subject),
  unique (tenant_id, id)
);

create table roles (
  id text primary key,
  tenant_id text not null references tenants(id),
  code text not null,
  name text not null,
  permissions jsonb not null default '[]'::jsonb,
  unique (tenant_id, code),
  unique (tenant_id, id)
);

create table user_roles (
  tenant_id text not null references tenants(id),
  user_id text not null,
  role_id text not null,
  valid_until timestamptz,
  primary key (tenant_id, user_id, role_id),
  foreign key (tenant_id, user_id) references users(tenant_id, id),
  foreign key (tenant_id, role_id) references roles(tenant_id, id)
);

create table data_scope_grants (
  id text primary key,
  tenant_id text not null references tenants(id),
  subject_type text not null check (subject_type in ('user', 'role', 'workspace')),
  subject_id text not null,
  scope_code text not null,
  scope_value text not null,
  unique (tenant_id, subject_type, subject_id, scope_code, scope_value)
);

create table agents (
  id text primary key,
  tenant_id text not null references tenants(id),
  name text not null,
  description text not null,
  welcome_message text,
  owner_user_id text not null,
  created_by text not null,
  status text not null check (status in ('draft', 'published', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, owner_user_id) references users(tenant_id, id),
  foreign key (tenant_id, created_by) references users(tenant_id, id)
);

create table agent_versions (
  id text primary key,
  tenant_id text not null references tenants(id),
  agent_id text not null,
  version text not null,
  system_prompt text not null,
  visible_role_ids jsonb not null default '[]'::jsonb,
  data_scopes jsonb not null default '[]'::jsonb,
  status text not null check (status in ('draft', 'published', 'disabled')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  unique (tenant_id, agent_id, version),
  unique (tenant_id, id),
  foreign key (tenant_id, agent_id) references agents(tenant_id, id)
);

create table skills (
  id text primary key,
  tenant_id text not null references tenants(id),
  key text not null,
  name text not null,
  owner_user_id text not null,
  status text not null check (status in ('draft', 'published', 'disabled')),
  unique (tenant_id, key),
  unique (tenant_id, id),
  foreign key (tenant_id, owner_user_id) references users(tenant_id, id)
);

create table skill_versions (
  id text primary key,
  tenant_id text not null references tenants(id),
  skill_id text not null,
  version text not null,
  instructions text not null,
  manifest jsonb not null default '{}'::jsonb,
  status text not null check (status in ('draft', 'published', 'disabled')),
  created_at timestamptz not null default now(),
  unique (tenant_id, skill_id, version),
  unique (tenant_id, id),
  foreign key (tenant_id, skill_id) references skills(tenant_id, id)
);

create table tools (
  id text primary key,
  tenant_id text not null references tenants(id),
  key text not null,
  name text not null,
  source text not null check (source = 'platform'),
  status text not null check (status in ('available', 'disabled')),
  unique (tenant_id, key),
  unique (tenant_id, id)
);

create table tool_versions (
  id text primary key,
  tenant_id text not null references tenants(id),
  tool_id text not null,
  version text not null,
  input_schema jsonb not null,
  output_schema jsonb not null,
  risk_level text not null check (risk_level in ('low', 'medium', 'high')),
  unique (tenant_id, tool_id, version),
  unique (tenant_id, id),
  foreign key (tenant_id, tool_id) references tools(tenant_id, id)
);

create table agent_version_skills (
  tenant_id text not null references tenants(id),
  agent_version_id text not null,
  skill_version_id text not null,
  primary key (tenant_id, agent_version_id, skill_version_id),
  foreign key (tenant_id, agent_version_id) references agent_versions(tenant_id, id),
  foreign key (tenant_id, skill_version_id) references skill_versions(tenant_id, id)
);

create table agent_version_tools (
  tenant_id text not null references tenants(id),
  agent_version_id text not null,
  tool_version_id text not null,
  primary key (tenant_id, agent_version_id, tool_version_id),
  foreign key (tenant_id, agent_version_id) references agent_versions(tenant_id, id),
  foreign key (tenant_id, tool_version_id) references tool_versions(tenant_id, id)
);

create table credential_refs (
  id text primary key,
  tenant_id text not null references tenants(id),
  backend text not null check (backend in ('dsh-managed', 'keychain', 'secret-manager')),
  external_ref text not null,
  status text not null check (status in ('configured', 'missing', 'revoked')),
  last_verified_at timestamptz,
  updated_by text,
  updated_at timestamptz not null default now(),
  unique (tenant_id, backend, external_ref),
  unique (tenant_id, id)
);

create table model_providers (
  id text primary key,
  tenant_id text not null references tenants(id),
  key text not null,
  name text not null,
  provider_type text not null,
  base_url text not null,
  credential_ref_id text,
  status text not null check (status in ('active', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, key),
  unique (tenant_id, id),
  foreign key (tenant_id, credential_ref_id) references credential_refs(tenant_id, id)
);

create table provider_models (
  id text primary key,
  tenant_id text not null references tenants(id),
  provider_id text not null,
  model_key text not null,
  display_name text not null,
  capabilities jsonb not null default '[]'::jsonb,
  status text not null check (status in ('active', 'disabled')),
  unique (tenant_id, provider_id, model_key),
  unique (tenant_id, id),
  foreign key (tenant_id, provider_id) references model_providers(tenant_id, id)
);

create table model_routes (
  id text primary key,
  tenant_id text not null references tenants(id),
  key text not null,
  name text not null,
  purpose text not null check (purpose in ('default', 'chat', 'analysis', 'fallback')),
  provider_model_id text not null,
  priority integer not null default 100 check (priority >= 0),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, key),
  unique (tenant_id, id),
  foreign key (tenant_id, provider_model_id) references provider_models(tenant_id, id)
);

create unique index model_routes_one_default
  on model_routes (tenant_id) where purpose = 'default' and enabled;

create table connectors (
  id text primary key,
  tenant_id text not null references tenants(id),
  key text not null,
  name text not null,
  connector_type text not null,
  credential_ref_id text,
  status text not null check (status in ('healthy', 'degraded', 'disabled')),
  unique (tenant_id, key),
  unique (tenant_id, id),
  foreign key (tenant_id, credential_ref_id) references credential_refs(tenant_id, id)
);

create table workspaces (
  id text primary key,
  tenant_id text not null references tenants(id),
  name text not null,
  description text not null default '',
  workspace_type text not null default 'team' check (workspace_type = 'team'),
  created_by text not null,
  status text not null check (status in ('active', 'archived')),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, created_by) references users(tenant_id, id)
);

create table workspace_members (
  tenant_id text not null references tenants(id),
  workspace_id text not null,
  user_id text not null,
  member_role text not null check (member_role in ('owner', 'admin', 'member', 'viewer')),
  added_by text not null,
  joined_at timestamptz not null default now(),
  primary key (tenant_id, workspace_id, user_id),
  foreign key (tenant_id, workspace_id) references workspaces(tenant_id, id),
  foreign key (tenant_id, user_id) references users(tenant_id, id),
  foreign key (tenant_id, added_by) references users(tenant_id, id)
);

create table workspace_capability_grants (
  tenant_id text not null references tenants(id),
  workspace_id text not null,
  capability_type text not null check (capability_type in ('agent', 'skill', 'tool')),
  capability_version_id text not null,
  primary key (tenant_id, workspace_id, capability_type, capability_version_id),
  foreign key (tenant_id, workspace_id) references workspaces(tenant_id, id)
);

create table sessions (
  id text primary key,
  tenant_id text not null references tenants(id),
  workspace_id text,
  created_by text not null,
  agent_version_id text not null,
  title text not null,
  status text not null check (status in ('active', 'archived')),
  last_active_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, workspace_id) references workspaces(tenant_id, id),
  foreign key (tenant_id, created_by) references users(tenant_id, id),
  foreign key (tenant_id, agent_version_id) references agent_versions(tenant_id, id)
);

create table messages (
  id text primary key,
  tenant_id text not null references tenants(id),
  session_id text not null,
  role text not null check (role in ('user', 'assistant', 'system', 'tool')),
  content text not null,
  content_classification text not null default 'internal',
  created_at timestamptz not null default now(),
  foreign key (tenant_id, session_id) references sessions(tenant_id, id)
);

create table runtimes (
  id text primary key,
  tenant_id text not null references tenants(id),
  node_name text not null,
  runtime_version text not null,
  health_status text not null check (health_status in ('healthy', 'degraded', 'offline')),
  scheduling_status text not null check (scheduling_status in ('accepting', 'draining', 'disabled')),
  capacity integer not null check (capacity > 0),
  last_heartbeat_at timestamptz,
  unique (tenant_id, id)
);

create table runtime_configurations (
  tenant_id text not null references tenants(id),
  revision integer not null check (revision > 0),
  concurrency_limit integer not null check (concurrency_limit > 0),
  timeout_seconds integer not null check (timeout_seconds > 0),
  sandbox_policy jsonb not null default '{}'::jsonb,
  updated_by text not null,
  updated_at timestamptz not null default now(),
  primary key (tenant_id, revision),
  foreign key (tenant_id, updated_by) references users(tenant_id, id)
);

create table runs (
  id text primary key,
  tenant_id text not null references tenants(id),
  session_id text not null,
  requested_by text not null,
  idempotency_key text not null,
  status text not null check (status in ('queued', 'running', 'cancel_requested', 'succeeded', 'failed', 'cancelled')),
  current_attempt_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant_id, session_id, requested_by, idempotency_key),
  unique (tenant_id, id),
  foreign key (tenant_id, session_id) references sessions(tenant_id, id),
  foreign key (tenant_id, requested_by) references users(tenant_id, id)
);

create table run_attempts (
  id text primary key,
  tenant_id text not null references tenants(id),
  run_id text not null,
  attempt_no integer not null check (attempt_no > 0),
  runtime_id text,
  manifest jsonb not null,
  manifest_sha256 text not null,
  model_route_snapshot jsonb not null,
  status text not null check (status in ('queued', 'running', 'cancel_requested', 'succeeded', 'failed', 'cancelled')),
  started_at timestamptz,
  ended_at timestamptz,
  error_code text,
  created_at timestamptz not null default now(),
  unique (tenant_id, run_id, attempt_no),
  unique (tenant_id, id),
  unique (tenant_id, run_id, id),
  foreign key (tenant_id, run_id) references runs(tenant_id, id),
  foreign key (tenant_id, runtime_id) references runtimes(tenant_id, id)
);

alter table runs add constraint runs_current_attempt_fk
  foreign key (tenant_id, current_attempt_id) references run_attempts(tenant_id, id)
  deferrable initially deferred;

create table run_events (
  id text primary key,
  tenant_id text not null references tenants(id),
  run_id text not null,
  attempt_id text not null,
  sequence bigint not null check (sequence > 0),
  event_type text not null,
  display_message text,
  safe_metadata jsonb not null default '{}'::jsonb,
  trace_id text not null,
  occurred_at timestamptz not null,
  unique (tenant_id, attempt_id, sequence),
  unique (tenant_id, id),
  foreign key (tenant_id, run_id) references runs(tenant_id, id),
  foreign key (tenant_id, run_id, attempt_id) references run_attempts(tenant_id, run_id, id)
);

create table approvals (
  id text primary key,
  tenant_id text not null references tenants(id),
  run_id text not null,
  event_id text,
  requested_action text not null,
  risk_level text not null check (risk_level in ('medium', 'high')),
  status text not null check (status in ('pending', 'approved', 'rejected', 'expired')),
  resolved_by text,
  resolved_at timestamptz,
  foreign key (tenant_id, run_id) references runs(tenant_id, id),
  foreign key (tenant_id, event_id) references run_events(tenant_id, id),
  foreign key (tenant_id, resolved_by) references users(tenant_id, id)
);

create table file_objects (
  id text primary key,
  tenant_id text not null references tenants(id),
  workspace_id text,
  session_id text,
  storage_key text not null,
  original_name text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  sha256 text not null,
  scan_status text not null check (scan_status in ('pending', 'clean', 'blocked', 'failed')),
  created_at timestamptz not null default now(),
  check (workspace_id is not null or session_id is not null),
  unique (tenant_id, id),
  foreign key (tenant_id, workspace_id) references workspaces(tenant_id, id),
  foreign key (tenant_id, session_id) references sessions(tenant_id, id)
);

create table artifacts (
  id text primary key,
  tenant_id text not null references tenants(id),
  workspace_id text,
  session_id text not null,
  name text not null,
  artifact_type text not null,
  created_by text not null,
  created_at timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, workspace_id) references workspaces(tenant_id, id),
  foreign key (tenant_id, session_id) references sessions(tenant_id, id),
  foreign key (tenant_id, created_by) references users(tenant_id, id)
);

create table artifact_versions (
  id text primary key,
  tenant_id text not null references tenants(id),
  artifact_id text not null,
  version_no integer not null check (version_no > 0),
  file_object_id text not null,
  source_run_id text not null,
  created_at timestamptz not null default now(),
  unique (tenant_id, artifact_id, version_no),
  foreign key (tenant_id, artifact_id) references artifacts(tenant_id, id),
  foreign key (tenant_id, file_object_id) references file_objects(tenant_id, id),
  foreign key (tenant_id, source_run_id) references runs(tenant_id, id)
);

create table model_usage_events (
  id text primary key,
  tenant_id text not null references tenants(id),
  run_id text not null,
  attempt_id text not null,
  provider text not null,
  model text not null,
  input_tokens bigint not null check (input_tokens >= 0),
  output_tokens bigint not null check (output_tokens >= 0),
  latency_ms integer check (latency_ms >= 0),
  cost_amount numeric(20, 8),
  cost_currency text,
  occurred_at timestamptz not null,
  foreign key (tenant_id, run_id) references runs(tenant_id, id),
  foreign key (tenant_id, attempt_id) references run_attempts(tenant_id, id)
);

create table tool_audit_logs (
  id text primary key,
  tenant_id text not null references tenants(id),
  run_id text not null,
  attempt_id text not null,
  tool_version_id text not null,
  actor_user_id text not null,
  parameter_summary jsonb not null default '{}'::jsonb,
  result text not null check (result in ('success', 'failed', 'blocked')),
  trace_id text not null,
  occurred_at timestamptz not null,
  foreign key (tenant_id, run_id) references runs(tenant_id, id),
  foreign key (tenant_id, attempt_id) references run_attempts(tenant_id, id),
  foreign key (tenant_id, tool_version_id) references tool_versions(tenant_id, id),
  foreign key (tenant_id, actor_user_id) references users(tenant_id, id)
);

create table audit_events (
  id text primary key,
  tenant_id text not null references tenants(id),
  actor_type text not null check (actor_type in ('user', 'super_admin', 'system')),
  actor_id text not null,
  action text not null,
  object_type text not null,
  object_id text not null,
  result text not null check (result in ('success', 'failed', 'blocked')),
  trace_id text not null,
  safe_context jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create table system_settings (
  tenant_id text not null references tenants(id),
  key text not null,
  value jsonb not null,
  revision integer not null default 1,
  updated_by text not null,
  updated_at timestamptz not null default now(),
  primary key (tenant_id, key),
  foreign key (tenant_id, updated_by) references users(tenant_id, id)
);

create index sessions_by_owner on sessions (tenant_id, created_by, last_active_at desc);
create index sessions_by_workspace on sessions (tenant_id, workspace_id, last_active_at desc);
create index runs_by_session on runs (tenant_id, session_id, created_at desc);
create index attempts_by_run on run_attempts (tenant_id, run_id, attempt_no desc);
create index events_by_attempt on run_events (tenant_id, attempt_id, sequence);
create index workspace_members_by_user on workspace_members (tenant_id, user_id, workspace_id);
create index artifacts_by_workspace on artifacts (tenant_id, workspace_id, created_at desc);
create index audit_by_time on audit_events (tenant_id, occurred_at desc);
create index audit_by_trace on audit_events (tenant_id, trace_id);
create index model_usage_by_time on model_usage_events (tenant_id, occurred_at desc);
create index model_usage_by_run on model_usage_events (tenant_id, run_id);

-- Published governance versions are immutable. Mutations are only allowed while draft.
create or replace function prevent_published_version_update() returns trigger language plpgsql as $$
begin
  if old.status = 'published' then
    raise exception 'published versions are immutable';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger agent_versions_immutable before update or delete on agent_versions
  for each row execute function prevent_published_version_update();
create trigger skill_versions_immutable before update or delete on skill_versions
  for each row execute function prevent_published_version_update();
